Fix and modernize nix builds to flake.nix + haskell.nix (#29)
This PR updates the nix build infrastructure to use flakes and haskell.nix through our new `hs-nix-infra` flake and converts default.nix to be a wrapper around the new `flake.nix`.

* Add a flake.nix that builds with haskell.nix

* Add sha256 to deeproute  source-repository-package

* Fix compiler-nix-name

* Set uppoer bound on aeson

Otherwise the build fails with:

[ 1 of 16] Compiling JsonRpc          ( src/JsonRpc.hs, dist/build/chainweb-mining-client/chainweb-mining-client-tmp/JsonRpc.o, dist/build/chainweb-mining-client/chainweb-mining-client-tmp/JsonRpc.dyn_o )

src/JsonRpc.hs:162:22: error:
    • Expecting one more argument to ‘A.KeyValue kv’
      Expected a constraint,
        but ‘A.KeyValue kv’ has kind ‘* -> Constraint’
    • In the type signature:
        requestProperties :: A.KeyValue kv =>
                             A.ToJSON a => T.Text -> a -> Maybe MsgId -> [kv]
    |
162 | requestProperties :: A.KeyValue kv => A.ToJSON a => T.Text -> a -> Maybe MsgId -> [kv]
    |                      ^^^^^^^^^^^^^

* Convert default.nix as legacy wrapper for flake.nix

* Switch to hs-nix-infra for pinning Haskell toolchain

* Add Nix build and cache action

* Add a recursive output

* Build recursive.allDerivations in CI

* Update setup-nix-with-cache

* Configure Nix with recursive-nix

* Switch back to hs-nix-infra/main

* Bump hs-nix-infra

* Turn default.nix into a function

In order to maintain backwards compatibility with old consumers